### PR TITLE
Add lint to detect manual slice copies

### PR DESCRIPTION
**Pull request by marcusklaas**
This PR replaces https://github.com/rust-lang-nursery/rust-clippy/pull/1937.

Addresses issue https://github.com/rust-lang-nursery/rust-clippy/issues/1831.

I see there are still some formatting issues. This PR has been formatted with the latest rustfmt (stable). I am receptive to instructions on how to fix these.

### CODE REVIEW

**Comment by oli-obk** [comment]
> This PR has been formatted with the latest rustfmt (stable).

It looks like you actually ran both (first nightly, then stable).

> I am receptive to instructions on how to fix these.

So I applied the method that I'd desire in situations like these directly to the PR:

1. A commit doing all the formatting without touching the files in any non-formatting way
2. A commit adding tests showing the false positives
3. A commit with the fixes and the updated tests

This makes it really easy to see the changes you did in the last commit, since the ui-tests don't show any line change noise

**Comment by oli-obk** [comment]
Did you ever address

> After a more detailed inspection of the documentation on clone_from_slice, I think the current lint suggestions may cause panics. The destination slice must apparently be exactly as long as the source. Also, it may be preferable to use copy_from_slice when T: Copy, although in my experience clone_from_slice also compiles to a memcpy in release builds.

in the previous PR? This PR looks good to me with the suggestion fixed to produce the same semantics as the loop.

**Comment by marcusklaas** [comment]
Thanks for the commits (I didn't know that was possible!) and the guidance!

I did address the panic situation. The destination slice should now always be as the source slice, although I did not make a separate commit for it.

**Comment by oli-obk** [comment]
Great!

Another lint that will have a positive impact on many projects. So much cool stuff in clippy lately

**Comment by marcusklaas** [comment]
👍

**Comment by Manishearth** [comment]
Wow this is a pretty sweet lint

**Pull request merged**
