### PR TITLE
Move shadow_unrelated to pedantic

### LINKED ISSUE #3012: Move `shadow_unrelated` to `pedantic`
rationale from https://github.com/rust-lang/rfcs/pull/2476#discussion_r206257168

> It actually is a useful bug-catcher, and it's not quite idiomatic to have unrelated shadows, though marginally so.

### PR DESCRIPTION
**Pull request by dwijnand**
Is this all that's required?

Fixes #3012

### CODE REVIEW

**Comment by flip1995** [comment]
You also have to move the lint into the correct lint group in the `lib.rs` file.

https://github.com/rust-lang-nursery/rust-clippy/blob/99a087bea59c8f808b5485c6113edf9ce774e94a/clippy_lints/src/lib.rs#L425

Running the `util/update_lints.py` script should do this for you!

**Comment by dwijnand** [comment]
Thanks @flip1995!

**Comment by flip1995** [comment]
LGTM! Waiting for Clippy master to build again and a CI rerun after that.

**Comment by dwijnand** [comment]
I suspected as much. Thanks for the review!

**Comment by dwijnand** [comment]
CI error looks unrelated. Let's try again.

**Pull request merged**
