### PR TITLE
Link to correct AppVeyor project in Readme

### LINKED ISSUE #2063: AppVeyor URL in README broken
The README's AppVeyor status links to <https://ci.appveyor.com/project/rust-lang-nursery/rust-clippy>, which just shows an error:

> Project not found or access denied.

### PR DESCRIPTION
**Pull request by phansch**
Fixes #2063

### CODE REVIEW

**Comment by phansch** [comment]
Looks like the image url is wrong :(

**Comment by phansch** [comment]
https://www.appveyor.com/docs/status-badges/

It looks like a secret token is required to fix the image URL, which should be on a 'Badges' tab in the AppVeyor project settings. The inferred link that is mentioned at the bottom of the docs doesn't work and shows 'unknown':

https://ci.appveyor.com/api/projects/status/github/rust-lang-libs/rust-clippy?svg=true&branch=master


@oli-obk  Do you have access to the project settings?

**Comment by oli-obk** [comment]
nope. Also [rls](https://github.com/rust-lang-nursery/rls) seems to have a similar problem

ping @nrc the appveyor story around nursery crates is a little odd. Can you delegate those powers so we can try to fix this on our side?

**Comment by nrc** [comment]
AIUI rust-lang-libs is the old name for the nursery repo and the only one that Appveyor knows about. So I think this PR should fix it.

I don't understand the other issue and what powers are needed to fix it (or even if I have those powers) - is it GH or Appveyor?

**Comment by oli-obk** [comment]
> I don't understand the other issue

Apparently there's a secret key that needs to be a part of all urls to badges. Even though the docs page says this shouldn't be needed for public repositories, it also says

> provided there is only a single project with this repository in AppVeyor.

which might be the issue, because there have been multiple `rust-clippy` that are built on appveyor.

So we possibly require the secret key, which is only available in the settings of appveyor.

> what powers are needed to fix it (or even if I have those powers) - is it GH or Appveyor?

Since logging into appveyor asks me whether I want to login as `rust-lang` or `oli-obk`, I'm assuming that `rust-lang-nursery` would be another option. So presumably it would be enough if I had `rust-lang-nursery` powers (which are needed I have no clue).

**Comment by mati865** [comment]
Maybe you could contact AppVeyor support?
They had really helpful people there a while back.

**Comment by phansch** [comment]
I contacted the AppVeyor support via their support forum, let's see what they say.

**Comment by phansch** [comment]
I got some clarifications from the AppVeyor support:

There are multiple rust-clippy projects on AppVeyor, so we can't use the public badge image, unfortunately (and that's probably why it always shows 'failed').

It should be possible to obtain the 'private' badge image URL from the 'Badge' tab in the project settings. The project settings should be on the right of "Latest Build" and "History", if you're logged in to AppVeyor.

This link should go directly to the badge page, if you're logged in and have access: https://ci.appveyor.com/project/rust-lang-libs/rust-clippy/settings/badges We would need the master branch SVG.

cc @nrc

**Comment by mati865** [comment]
Friendly ping @nrc

**Comment by nrc** [comment]
Testing: [Build status](https://ci.appveyor.com/project/rust-lang-libs/rust-clippy)

**Comment by nrc** [comment]
that worked!

@phansch you should be able to use the following:

```
[![Build status](https://ci.appveyor.com/api/projects/status/id677xpw1dguo7iw?svg=true)](https://ci.appveyor.com/project/rust-lang-libs/rust-clippy)
```

Sorry that took so long, I missed most of this thread.

**Comment by phansch** [comment]
@nrc Awesome, thanks!

**Pull request merged**
