### PR TITLE
stabilizing feature iterator_for_each for rust 1.22.0

### PR DESCRIPTION
**Pull request by budziq**
It's my first rust stabilization PR and it's with submodules to boot so might have done something completely wrong. Sorry for that!

### CODE REVIEW

**Comment by budziq** [comment]
I guess that this change might go to a separate branch until https://github.com/rust-lang/rust/pull/44567 is merged as was the case for identical PR for RLS. Please let me know if any additional action is needed on my part.

**Comment by Manishearth** [comment]
retriggering travis

**Comment by Manishearth** [comment]
ah, looks like a test needed updated line numbers. fixed.

**Comment by oli-obk** [comment]
@Manishearth you forgot to push your fixes

**Comment by Manishearth** [comment]
Fix was 04c44fa3, looks like I landed it and this PR directly as 44ecc19a3f25f8741736c05c477047386ff9f2fb . Probably did a rebase and forgot to update the PR. It's merged

**Pull request closed without merging**
