### PR TITLE
Replace cfg_attr(rustfmt... with rustfmt::skip

### LINKED ISSUE #2822: Replace all our `cfg_attr(rustfmt...` thingies with `#[rustfmt::foo]`
Yes `thingies` are a thing.

A simple search and replace should totally suffice

### PR DESCRIPTION
**Pull request by flip1995**
Fixes #2822 

`thingies` replaced!

### CODE REVIEW

**Comment by oli-obk** [comment]
still triggering some errors on travis

**Comment by flip1995** [comment]
This is a rustc problem. If you enable the `rust_2018_preview` and the `tool_attributes` feature, the `tool_attributes` stop working, see [playground](https://play.rust-lang.org/?gist=5e58bba0f9cde9deb1a0a60c7b604d6a&version=nightly&mode=debug). I'm looking into this tomorrow and either open a PR or an issue.

**Comment by mati865** [comment]
:disappointed:
The migration took it's first casualty.

**Comment by mati865** [comment]
This PR will be unblocked when https://github.com/rust-lang/rust/pull/52841 lands.

**Comment by mati865** [comment]
CI passed

**Pull request merged**
