### PR TITLE
Fix #1142 float constant comparison lint

### LINKED ISSUE #1142: float_cmp: ignore when comparing with constant?
Consider:

```
const ONE: f32 = 1.0;
fn main() {
    let v = 0.9;
    let _ = v == ONE;
}
```

These are probably cases where you want to check for the exact constant, because it is a common argument, a sentinel value, or an integer converted to floating-point due to external APIs, etc.

There is already a special case for 0 and +/-inf, but I'd add a case for this situation too.

### PR DESCRIPTION
**Pull request by clippered**
Fix #1142: @oli-obk  just made a new restriction lint as mentioned. I'm still not sure if I got the stuff needed to define a new lint, like the names, docs, conventions, etc. This is ready for review, and I'm open for feedback, thanks.

### CODE REVIEW

**Comment by oli-obk** [comment]
The lint and tests looks great. Can you just add some "negative" tests, too? So something that tests that the lint doesn't trigger on `v == w` if both are floats? And what happens on `v == 1.0`?

**Comment by clippered** [comment]
Thanks for your inputs, I just added more tests. now waiting
v==w and v==1.0 will just trigger the 'float_cmp' lint.

**Comment by oli-obk** [comment]
Cool. I think it would be best if we ignored the `float_cmp` lint in this file. They are tested in other files.

**Comment by clippered** [comment]
Thanks for that. now just waiting for CI to complete.

**Comment by oli-obk** [comment]
Oh... sorry, that's not what I meant. add `allow(float_cmp)`, and keep the tests. This way they don't show up in the `stderr` file.

**Comment by clippered** [comment]
i see, will get back in a couple of hours then

**Comment by oli-obk** [comment]
Whoops, forgot about this PR. Luckily it still compiles :D

**Pull request merged**
