### PR TITLE
Lint range_plus_one and range_minus_one (closes #329)

### LINKED ISSUE #329: x..(y+1) reads better as x...y
Once we have inclusive ranges (which won't be too long; the RFC has recently been accepted), I think we should advise people to use them.

Perhaps we could also check for `x...(y-1)` while we're at it.

### PR DESCRIPTION
**Pull request by niklasf**
Attempting to implement the idea from #329.

### CODE REVIEW

**Comment by oli-obk** [comment]
Cool! Can you add some tests? We should also make this allow by default, since inclusive range syntax isn't stable yet

**Comment by niklasf** [comment]
I've added some examples to `tests/ui/range_plus_minus_one.rs`. Do I have to do anything else, for example to get an `.stderr` file? `./tests/ui/update-all-references.sh tests/ui/` seems to immediately exit doing nothing.

**Comment by oli-obk** [comment]
You need to run cargo test first before running the script without any arguments

**Comment by oli-obk** [comment]
Thanks for the new lints. We'll turn it to warn by default once the syntax is stable

**Pull request merged**
