### PR TITLE
clippy_lints: enable crate_visibility_modifier since it is used but no longer part of 2018 edition.

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Fixes build with https://github.com/rust-lang/rust/pull/53999

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@Manishearth @oli-obk I think the AppVeyor failure is spurious -- can we get this landed relatively quickly? We'll need this to land and update the submodule in rust-lang/rust for the edition RC release.

**Comment by matthiaskrgr** [comment]
The appveyor failure is not spurious but expected and unrelated https://github.com/rust-lang-nursery/rust-clippy/issues/3118 . And Travis ci still passes anyway :)

**Comment by mati865** [comment]
@Mark-Simulacrum you can pin Clippy version to this PR and leave comment here to not rebase it.

**Comment by Mark-Simulacrum** [comment]
I would rather not release Rust compilers that look at PR branches, especially ones not in the rust-lang-nursery repository.

**Pull request merged**
