### PR TITLE
Move default_trait_access to pedantic

### PR DESCRIPTION
**Pull request by Manishearth**
This is a pretty common pattern, I think.

### CODE REVIEW

**Comment by oli-obk** [comment]
@illicitonion you created the lint, do you have any arguments to discuss before we merge this?

**Comment by illicitonion** [comment]
Sounds reasonable :)

I would be more comfortable leaving it as a clippy_lint if clippy could generate patches and auto-apply them to code, rather than requiring intervention - I think this is always a net improvement to code quality, but agree that it's not necessarily a big enough improvement for manual intervention. Is there any thought about patch generation?

**Comment by mati865** [comment]
@illicitonion rustup used to automagically fix most of clippy suggestions but lost this feature during refactors.
I think there was discussion whether it should be restored or implemented in clippy but I'm not sure about the final result.

cc @killercup

**Comment by Manishearth** [comment]
Yes, rustfix can fix these, provided clippy emits suggestions. This is actually hard to emit a suggestion for since you need an import as well.

**Pull request merged**
