### PR TITLE
Fix lint_without_lint_pass

### PR DESCRIPTION
**Pull request by mikerite**

### CODE REVIEW

**Comment by mikerite** [comment]
Looks like I broke something. I'll try again tomorrow.

**Comment by flip1995** [comment]
Not only the declared lint collection was broken, but also the registered lint collection. The old code of the registered lint collection seemed a little bit weird to me, so I decided to rewrite it.

**Comment by flip1995** [comment]
Oh @mikerite sorry I stole this from you, but this lint triggered or didn't trigger in weird ways and I wanted to look into this myself. cc https://github.com/rust-lang-nursery/rust-clippy/issues/3367#issuecomment-433842664

**Comment by mikerite** [comment]
No problem. Your changes look good to me.

**Pull request merged**
