### PR TITLE
Set RUSTC_WRAPPER instead of RUSTC when invoking Cargo

### PR DESCRIPTION
**Pull request by Aaron1011**
Some build scripts rely on the RUSTC binary being the actual compiler
(e.g. parsing the output of 'RUSTC --version'). To prevent clippy from
breaking these build scripts, this commit sets RUSTC_WRAPPER instead.
This will cause Cargo to leave RUSTC unchanged, making the use of clippy
transparent to build scripts.

### CODE REVIEW

**Comment by Aaron1011** [comment]
I'm unsure why the test passed on linux, but not OSX.

**Comment by oli-obk** [comment]
Just a new nightly that broke clippy...

**Comment by Aaron1011** [comment]
Rebased against master.

**Comment by oli-obk** [comment]
Thanks! This has been a longstanding issue. Good that there's finally a solution

**Pull request merged**
