### PR TITLE
fix lint array syntax

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**

### CODE REVIEW

**Comment by oli-obk** [comment]
Why is this necessary?

**Comment by oli-obk** [comment]
I cannot reproduce on linux. Which nightly version are you on?

**Comment by MarcAntoine-Arnaud** [comment]
On OSX: rustc 1.24.0 (4d90ac38c 2018-02-12)

**Comment by oli-obk** [comment]
Ah, that seems to be the issue. If you want to use the latest clippy, you also need to use the latest nightly.

See the docs for details: https://github.com/rust-lang-nursery/rust-clippy#usage

If you are looking for the clippy version that works with your nightly, there might not be one, but if there is, you can find it in https://github.com/rust-lang-nursery/rust-clippy/blob/master/CHANGELOG.md

**Comment by MarcAntoine-Arnaud** [comment]
Okay thx.

**Pull request closed without merging**
