### PR TITLE
rustup, fix breakage introduced by https://github.com/rust-lang/rust/pull/53581

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Is there a way to run the tests from the rustc repos clippy_lints package?

### CODE REVIEW

**Comment by Manishearth** [comment]
> Is there a way to run the tests from the rustc repos clippy_lints package?

Why? Just run the tests from this repo?

If you need a rustc to run this with, use https://github.com/kennytm/rustup-toolchain-install-master (`rustup-toolchain-install-master -n master -f`)

**Comment by matthiaskrgr** [comment]
Ok, I got it to build but a lot of tests fail, it looks like run-pass chooses the wrong compiler (nightly instead of master) :man_shrugging:

**Comment by matthiaskrgr** [comment]
AAAAH the ````rust-toolchain```` file was overriding back to ````nightly```` behind my back....

I removed it for testing, and all tests pass except for dogfood

````
Caused by:
  process didn't exit successfully: `/home/matthias/vcs/github/rust-clippy/target/debug/clippy-driver /home/matthias/.rustup/toolchains/master/bin/rustc - --crate-name ___ --print=file-names -C target-cpu=native --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 101)
--- stderr
error: multiple input filenames provided
````

**Comment by matthiaskrgr** [comment]
(However since clippy compiled fine I assume that this is only due to me using the rustc master version wrongly)

**Comment by flip1995** [comment]
Have you tried `cargo +master test` or how it should be done in CI one day: setting `rustup default master` and then just `cargo test`?

**Comment by matthiaskrgr** [comment]
Ok, I found my mistake, all tests pass now :tada:

**Comment by flip1995** [comment]
Thanks, the tool_attributes feature stabilization was merged a few hours ago. I added that here.

All tests pass for me locally

**Pull request merged**
