### PR TITLE
Unfinished : Lint `float_excessive precision`

### PR DESCRIPTION
**Pull request by gbip**
Hello,
I would like some advice on implementing this lint (related issue : #1806 ). The current code is not very concise, I plan on reducing it later, when it behaves correctly.
Do you think that it should visit recursively arrays and tuples ?
And, for the linting part, how do you think should the suggested float be stylized ? Should it respect the original style ? Should it always group digits ? What about suffixing it with f32 or f64 ?

### CODE REVIEW

**Comment by oli-obk** [comment]
Sorry, this PR fell under my radar

> Do you think that it should visit recursively arrays and tuples ?

Yes. You can use https://michael-f-bryan.github.io/rustc-internal-docs/rustc/mir/visit/trait.Visitor.html to automate the recursion.

Can you generate the `.stderr` file so we can see the output? run the script `test/ui/update-all-references.sh` after `cargo test`

**Comment by oli-obk** [comment]
Ping @gbip

**Comment by gbip** [comment]
I don't have time to work on this anymore... Sorry guys.

**Comment by estk** [comment]
I'm interested in taking this one on. Thinking I'll have a chance to work on it over the weekend.

**Pull request closed without merging**
