### PR TITLE
Fix logic that determines closest parent crate when invoked from a subdirectory.

### PR DESCRIPTION
**Pull request by Arnavion**
The previous logic incorrectly matches the deepest child of the current directory that is a crate.

Ref https://github.com/Manishearth/rust-clippy/pull/1860#issuecomment-316806919

cc @Vurich

### CODE REVIEW

**Comment by Arnavion** [comment]
Ping. clippy is broken for workspaces without this fix.

**Comment by oli-obk** [comment]
I restarted Travis.

**Comment by Arnavion** [comment]
When I wrote that comment I also pushed a rebased commit that had its own run, so your restart will still fail the same way (#1885 I assume).

**Comment by oli-obk** [comment]
Oh... that's weird. Well I won't be on a PC until tomorrow. I'll check it out then and publish

Can you add a call to Travis that runs cargo clippy after the normal run, but this time from a subdir? I fear if we don't test it it'll just break again.

**Comment by Arnavion** [comment]
Okay, I'll make one.

**Comment by Arnavion** [comment]
So doing it with clippy itself doesn't work because clippy is not the workspace root (it's part of clippy_tests workspace). Doing it with clippy_tests doesn't work because that is a lib crate, not a bin crate. So I made a new directory just for this test.

btw, I'm not sure how Travis treats current directory across multiple "scripts" in .travis.yml. If the current directory persists then I think the `cd ..` at the end of each script should be done with ';' instead of `&&` so that it runs even if the `cargo clippy` failed (so that the subsequent tests have current directory set correctly). If the current directory *doesn't* persist then there's no need to do `cd ..` at all?

**Comment by oli-obk** [comment]
Thanks!

**Pull request merged**
