### PR TITLE
Closes #1219 false positive for explicit_counter_loop

### LINKED ISSUE #1219: explicit_counter_loop false positive with continue statement
Clippy shows a false positive in this example, asking for an `explicit_counter_loop` refactor:

```
    let text = "banana";
    let mut count = 0;
    for ch in text.chars() {
        if ch == 'a' {
            continue;
        }
        count += 1
    }
    println!("{}", count);
```

But since the `continue` statement skips the counter, the proposed `for (count, ch) in text.char_indices()` is not equivalent.

### PR DESCRIPTION
**Pull request by JoshMcguigan**
Hello,

As in #3131, I added a test case here based on the reported issue #1219, and I'm not seeing a test failure. I am new to the clippy codebase, so please let me know if I am just missing something obvious.

Thanks!

### CODE REVIEW

**Comment by JoshMcguigan** [comment]
It looks like the integration test for RLS timed out after exactly 10 minutes. Looking at other builds it seems that test commonly runs long, can we re-run the build or is there something I should look into?

**Comment by phansch** [comment]
Restarted the RLS build, sometimes they just don't start.

I'm not really sure why the false positive is not triggered anymore.
Maybe I'm also doing something wrong, but this snippet should trigger the lint for sure:

```rust
fn main() {
    let text = "banana";
    let mut count = 0;
    for ch in text.chars() {
        if ch == 'a' {
            println!("abc")
        }
        count += 1
    }
    println!("{}", count);
}
```

And it doesn't: https://play.rust-lang.org/?gist=8081f695a48d99e0fe4e3e127b2cf781&version=nightly&mode=debug&edition=2015

**Comment by phansch** [comment]
It looks like we have very low test coverage for that lint. I only found these two tests that trigger the lint:

https://github.com/rust-lang-nursery/rust-clippy/blob/ca753c4af1c0b6db9c17324695750990bd472ed2/tests/ui/for_loop.rs#L267-L277

**Comment by oli-obk** [comment]
Maybe the lint is allow-by-default and needs a `warn` attribute to trigger?

**Comment by JoshMcguigan** [comment]
> Maybe the lint is allow-by-default and needs a warn attribute to trigger?

The playground link by @phansch includes an explicit `#![deny(clippy::explicit_counter_loop)]`.

I also tried the other test cases listed above and they aren't triggering the lint in the [playground](https://play.rust-lang.org/?gist=97ab6c4767868d19d7fff7d58c5e6dd2&version=nightly&mode=debug&edition=2015) either. Testing locally, I found that the following DO trigger the lint:

```
 // Loop with explicit counter variable 
 let mut _index = 0; 
 for _v in &vec { 
     _index += 1 
 } 
  
 let mut _index = 1; 
 _index = 0; 
 for _v in &vec { 
     _index += 1 
 } 
```

while these DO NOT trigger the lint:

```
    let text = "banana";
    let mut count = 0;
    for ch in text.chars() {
        if ch == 'a' {
            println!("abc")
        }
        count += 1
    }
    println!("{}", count);

    let thing = 5;
    let text = "banana";
    let mut count = 0;
    for ch in text.chars() {
        if ch == 'a' {
            continue;
        }
        count += 1
    }
    println!("{}", count);
```

I'll take a look and try to figure out why.

**Comment by flip1995** [comment]
Ah so the lint doesn't get triggered if the count variable gets used after the loop, which makes sense. If we would define the count variable in the loop decl, it would not be usable after the loop body.

Also adding `let _ = count;` after the loop prevents the lint from triggering.

Yep: #473

**Comment by flip1995** [comment]
> This commit corrects the bug where using the variable after the loop prevents the lint from triggering

This wasn't a bug, but intended. See PR #473 and corresponding issues #384 and #373 

The only ~~"bug"~~ feature is, that it is triggered when using `continue` without using the variable after the loop:
```rust
fn main() {
    let text = "banana";
    let mut count = 0;
    for ch in text.chars() {
        if ch == 'a' {
            continue;
        }
        count += 1
    }
}
```
But if you don't use the count variable after the loop, I don't think this is a FP, because you can use `.enumerate()` regardless of the `continue`, without changing the behavior.

**Comment by JoshMcguigan** [comment]
>This wasn't a bug, but intended. See PR #473 and corresponding issues #384 and #373

Thanks for setting me straight here, I misread your first post. 

>The only "bug" feature is, that it is triggered when using continue without using the variable after the loop...But if you don't use the count variable after the loop, I don't think this is a FP...

So this issue can be closed then? Or perhaps we add some tests here to ensure the appropriate coverage and link them to these issues?

**Comment by flip1995** [comment]
Yes, I think this issue is resolved. But adding some tests for future reference is always good. It would be great if you could do this!

**Comment by JoshMcguigan** [comment]
I've updated the tests, but looking at it again I'm thinking there is still a false positive here. Modifying the example code from @flip1995 slightly:

```
let text = "banana";
let mut count = 0;
for ch in text.chars() {
    if ch == 'a' {
        continue;
    }
    count += 1;
    println!("{}", count);
}
```

Currently this triggers the lint, but using enumerate here would change the behavior. @flip1995 can you confirm I am thinking about this correctly?

**Comment by flip1995** [comment]
Yes this is a FP! [Playground](https://play.rust-lang.org/?gist=ae96fc850695b31c70cf03e1bb413679&version=nightly&mode=debug&edition=2015)
Thanks for adding the tests and finding it! Do you like to try and fix this?

**Comment by JoshMcguigan** [comment]
I've corrected the behavior we discussed above, as well adding two more tests and corrected handling of nested loops as shown below.

```
// should trigger the lint because the count is not conditional
let text = "banana";
let mut count = 0;
for ch in text.chars() {
    count += 1;
    for i in 0..2 {
        let _ = 123;
    }
    println!("{}", count);
}

// should not trigger the lint because the count is incremented multiple times
let text = "banana";
let mut count = 0;
for ch in text.chars() {
    count += 1;
    for i in 0..2 {
        count += 1;
    }
    println!("{}", count);
}
```

If all this looks good to you, I believe this is fit to be merged.

**Pull request merged**
