### PR TITLE
Try to fix issue #1824

### PR DESCRIPTION
**Pull request by messense**
Addresses #1824

### CODE REVIEW

**Comment by oli-obk** [comment]
While this fixes this one specific crash, we should fix the visitor. Accessing `cx.tables` in a visitor is absolutely wrong and we should probably write a lint that forbids us to do this (there's several more issues due to other visitors doing this). Instead we need to store a table in the visitor struct and update and restore it in `visit_body`.

**Comment by mcarton** [comment]
> Accessing `cx.tables` in a visitor is absolutely wrong […] there's several more issues due to other visitors doing this

Such as? Do we have issues for that specific problem?

**Comment by oli-obk** [comment]
E.g. https://github.com/Manishearth/rust-clippy/issues/1782 and we already have a few correct visitors

We don't have a meta issue

**Comment by oli-obk** [comment]
closing in favour of #1977

**Pull request closed without merging**
