### PR TITLE
Run travis on rustc master instead of nightlies

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by oli-obk** [comment]
@kennytm `rustup-toolchain-install-master` keeps randomly failing in our CI in the middle of downloading:

```
downloading <https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/15add366faac554db51244d1e27e4d10a08ab6e8/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz>...
23.66 MB / 71.84 MB [===========>------------------------] 32.93 % 5.65 MB/s 9s thread 'main' panicked at 'flush() fail', 
```

Any suggestions other than putting it in a loop until it succeeds?

**Comment by kennytm** [comment]
@oli-obk I'll take a look. `flush() fail`? 🤔

**Comment by phansch** [comment]
Just noting that there's [`travis_retry`](https://docs.travis-ci.com/user/common-build-problems/#travis_retry), so on Travis we would not have to implement the loop ourselves.

**Comment by phansch** [comment]
Looks like it fails even with the retries: https://travis-ci.org/rust-lang-nursery/rust-clippy/builds/376756827#L735-L747

**Comment by kennytm** [comment]
I've published `rustup-toolchain-install-master 0.2.0` which should have [fixed the issue](https://travis-ci.org/rust-lang-nursery/rust-clippy/builds/376756815).

**Comment by Manishearth** [comment]
Moved over to #2940, the merge conflict here is weird because of the first commit (?)

**Pull request closed without merging**
