### PR TITLE
Start working on #1590

### PR DESCRIPTION
**Pull request by gendx**
I started working on #1590. However, I didn't find how to trigger the UI tests that I wrote for my new lint.

### CODE REVIEW

**Comment by sinkuu** [comment]
You have to register your lint in these places.

https://github.com/rust-lang-nursery/rust-clippy/blob/306b6e243b384570804585499c492e80436db885/clippy_lints/src/lib.rs#L352
https://github.com/rust-lang-nursery/rust-clippy/blob/306b6e243b384570804585499c492e80436db885/clippy_lints/src/lib.rs#L507

**Comment by gendx** [comment]
Thanks! This should be fixed now.

**Comment by oli-obk** [comment]
Wow! Your first lint and I can't even find a nit to complain about ;)

**Comment by gendx** [comment]
Thanks! To be fair most of the implementation was already in the `Option` version ;) So it was a good way to begin with clippy's internals!

**Pull request merged**
