### PR TITLE
iter conservation efforts: save the endangered .iter() and .into_iter()

### PR DESCRIPTION
**Pull request by joshtriplett**
```
 ______________________________________
/ It looks like you're writing a loop. \
\ Would you like some help?            /
 --------------------------------------
 \
  \
     __
    /  \
    |  |
    @  @
    |  |
    || |/
    || ||
    |\_/|
    \___/
```

Every day, more iters are lost, discarded as unwanted, to such hazards
as "concision" and "brevity". Won't someone think of the poor .iter()
and .into_iter(), that future generations may continue to admire them
and their self-documenting properties in their many and varied natural
habitats, and not merely in a zoo of (en)closures?

Make explicit_iter_loop and explicit_into_iter_loop allow-by-default, so
that people can turn them on if they want to enforce that style; avoid
presenting them as *the* idiomatic Rust style, rather than just *a* style.

### CODE REVIEW

**Comment by flip1995** [comment]
Also needs to be updated in `clippy_lints/src/lib.rs`. Running `utils/update_lints.py` should do this.

**Comment by joshtriplett** [comment]
@flip1995 Done, thanks.

**Comment by flip1995** [comment]
Oh and the `stderr` file needs to be updated:
```bash
tests/ui/update-references.sh 'target/debug/test_build_base' 'for_loop.rs'
```

**Comment by joshtriplett** [comment]
(The appveyor failure looks spurious.)

**Comment by flip1995** [comment]
Thanks!

Appveyor error is unrelated: #3118

**Comment by Manishearth** [comment]
@joshtriplett could you leave the requested comment on #3230 ? This is a minor PR so it doesn't really count, but might as well get the sign off if I can :smile:

**Comment by joshtriplett** [comment]
On October 2, 2018 4:44:13 AM PDT, Manish Goregaokar <notifications@github.com> wrote:
>@joshtriplett could you leave the requested comment on #3230 ? This is
>a minor PR so it doesn't really count, but might as well get the sign
>off if I can :smile: 

Done.

**Pull request merged**
