### PR TITLE
make ci use master rustc instead of nightly

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Ah I can also revert the hyper disabling, will do in a couple mins.

**Comment by flip1995** [comment]
Nice! r=me with hyper enabled and CI pass

This also closes #3383 and #3370 should be mergable

**Comment by matthiaskrgr** [comment]
Ah good point.. We have to wait for nightly to build the toolchain installer to get master...
So ~10-12 hours to go.. :)

**Comment by matthiaskrgr** [comment]
bors r=flip1995

**Pull request merged**
