### PR TITLE
Change all links to reflect the move to rust-lang-nursery

### PR DESCRIPTION
**Pull request by llogiq**
A lot of links still point to https://github.com/Manishearth/rust-clippy so this PR moves them to our new repo 
URL.

r? @Manishearth

### CODE REVIEW

**Comment by killercup** [comment]
My suggestion to rename the repo to rust-lang-nursery/clippy was serious, btw

**Comment by llogiq** [comment]
I'm not sure, but I think only Manish (as the owner of this repo) can do that. I'm just reflecting the current change with this PR.

**Comment by llogiq** [comment]
@Manishearth do you plan to move the repo to `rust-lang-nursery/clippy`? If so I can update the PR.

**Comment by Manishearth** [comment]
Don't particularly plan to, but I'm open to it.

I'm kinda afraid that two moves will break redirects.

**Comment by killercup** [comment]
In other Github projects, several historical URLs redirect to the current
one without problems. (Not an official confirmation just a data point.)

Manish Goregaokar <notifications@github.com> schrieb am Di. 8. Aug. 2017 um
22:14:

**Comment by oli-obk** [comment]
There's many other `rust-*` projects in the `rust-lang-nursery` orga. While it would be neat to have a more concise name, I'm not feeling particularly strong about it. But we should decide on it now imo. I also don't think that redirects are an issue. I still have some bookmarks to horribly outdated repo names and they work just fine after years.

**Comment by oli-obk** [comment]
ping @Manishearth 

There seems to be a small preference for renaming to `clippy`, and so far no outspoken opponents.

**Comment by frewsxcv** [comment]
Can we do the repo name bikeshedding in a separate issue? It doesn't seem like that should be blocking this PR

**Pull request merged**
