### PR TITLE
Add misaligned_transmute lint

### LINKED ISSUE #1384: Lint transmutes from potentially lesser-aligned pointers
This could lead to hard to debug alignment failures. I think it should be possible to extend our current lints around transmutes. 

(See https://github.com/rust-lang/rust/pull/38352#discussion_r92238154)

### PR DESCRIPTION
**Pull request by devonhollowood**
Fix #1384

### CODE REVIEW

**Comment by Manishearth** [comment]
Thanks!

**Comment by sellibitze** [comment]
I came from [here](https://www.reddit.com/r/rust/comments/7sq8xl/unsafe_zig_is_safer_than_unsafe_rust/dt96k0f/) and noticed that the test in transmute.rs includes

```
let _: u32 = unsafe { std::mem::transmute([0u8; 4]) }; // err
```

But I don't actually see an alignment problem here as `_` would get its own properly aligned storage.

Alignment is usually an issue when pointers & references are involved, e.g. creating a `&T` from an `&U` where `T` has higher alignment requirements than `U`.

**Comment by oli-obk** [comment]
Indeed, this should probably be alright. I say "probably", because the semantics of `transmute` are severely underspecified. Feel free to constrain the lint to references or things containing references.

**Comment by devonhollowood** [comment]
@sellibitze @oli-obk Are you sure? Maybe I am misreading this assembly, but for example in this function the `[u8; 4]` doesn't look like it gets copied:

Rust:
```rust
pub fn foo(input: &[u8; 4]) -> bool {
    let y: u32 = unsafe {std::mem::transmute(*input)};
    y == 123456
}
```

x86 (compiled with `-O`):
```Assembly
example::foo:
  push rbp
  mov rbp, rsp
  cmp dword ptr [rdi], 123456
  sete al
  pop rbp
  ret
```

[Compiler Explorer link](https://godbolt.org/g/bCL5ch)

**Comment by oli-obk** [comment]
@devonhollowood the `u32` still needs to be aligned. Irrelevant where its bits come from

**Comment by devonhollowood** [comment]
@oli-obk I think I was somewhat unclear. I agree that the `u32` needs to be aligned--the point I am trying to make is that I think this lint is still relevant for situations that don't contain references.

**Comment by oli-obk** [comment]
I don't know enough assembler to make a qualified statement about that.

Is the `edi` register 4 byte aligned?

**Comment by sellibitze** [comment]
@devonhollowood: Very interesting! I guess LLVM optimizes the temporary away and directly accesses the `[u8; 4]`'s memory as a `u32` in your first `foo` function under the assumption that the alignment *is* compatible. I'd say the implementation of `mem::transmute` is broken in that it allows LLVM to do this kind of optimization. It's time to summo the compiler gurus, I guess. :)

@oli-obk: registers don't have addresses themselves, just names. But edi could store an odd memory address that points to a `[u8;4]` in which case `dword ptr [edi]` wold be a misaligned memory access.

**Comment by oli-obk** [comment]
that means we're on the safe side assuming that small align -> large align transmutes are wrong?

**Comment by sellibitze** [comment]
I maintain that

```
pub fn foo(input: &[u8; 4]) -> bool {
    let y: u32 = unsafe {std::mem::transmute(*input)};
    y == 123456
}
```

is (or at least should be) perfectly OK and no error. Its observable behaviour is just implementation-defined (depending on the endianness). `mem::transmute` is defined in terms of *copying* raw bits. The source/target type's alignment doesn't matter.

The assembly code we've seen is what LLVM comes up with *after* optimization. It made the program access the possibly unaligned memory via `dword ptr [edi]`. *But* ... IIRC that's *fine* on x64 architectures. So, I don't think this assembly code proves much.

**Comment by devonhollowood** [comment]
@sellibitze Okay, so I went back and re-read the relevant docs.

[The `transmute` docs](https://doc.rust-lang.org/std/mem/fn.transmute.html) say

> `transmute` is semantically equivalent to a bitwise move of one type into another. It copies the bits from the source value into the destination value, then forgets the original. It's equivalent to C's `memcpy` under the hood, just like `transmute_copy`

[The nomicon section on transmute](https://doc.rust-lang.org/nomicon/transmutes.html) doesn't mention alignment.

[The Rust Reference's list of UB](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) says:

> Rust code, including within unsafe blocks and unsafe functions is incorrect if it exhibits any of the behaviors in the following list. It is the programmer's responsibility when writing unsafe code that it is not possible to let safe code exhibit these behaviors.
> 
> - ...
> - Unaligned pointer reading and writing outside of read_unaligned and write_unaligned.
> - ...

Because this so specifically only refers to referencing unaligned *pointers*, and because transmute is defined to be equivalent to `memcpy` (instead of just reinterpreting the underlying bytes), I think you are right: my two examples really are safe, and this lint should be restricted to just pointer types.

**Pull request merged**
