### PR TITLE
Document how to lint local Clippy changes with locally built Clippy

### PR DESCRIPTION
**Pull request by waynr**

### CODE REVIEW

**Comment by mati865** [comment]
Doesn't `cargo test` already do it?

**Comment by waynr** [comment]
@mati865 I see that there is a ["dogfood" test case](https://github.com/rust-lang-nursery/rust-clippy/blob/master/tests/dogfood.rs), but it's not quite the same as the command shown in this PR and it doesn't seem to report when the command shown in this PR does. For an example of when I would expect a problem to be reported by the command shown in this PR, see this PR:
https://github.com/rust-lang-nursery/rust-clippy/pull/3437/commits

And specifically, compare the result of `cargo test` and the command I added in this PR when run against this commit: 
https://github.com/rust-lang-nursery/rust-clippy/pull/3437/commits/ca4803101f95455b0436cefdf0e7cfecf259ca97

Maybe we could fix the dogfood test case and remove https://github.com/rust-lang-nursery/rust-clippy/blob/64ff255ac63856c1dfe2021a62349984e4039788/ci/base-tests.sh#L30-L32/

**Comment by flip1995** [comment]
dogfood should do that but it seems that dogfood doesn't catch as many errors as running clippy itself.

See
https://travis-ci.org/rust-lang-nursery/rust-clippy/jobs/457767388#L1474
vs
https://travis-ci.org/rust-lang-nursery/rust-clippy/jobs/457767388#L1211

**Comment by flip1995** [comment]
> Maybe we could fix the dogfood test case and remove

That would be a good solution. But as long as dogfood doesn't behave as it should, we should add this to the docs.

bors r+

**Pull request merged**
