### PR TITLE
Remove dependence of ci on github token

### PR DESCRIPTION
**Pull request by Manishearth**
r? @phansch

### CODE REVIEW

**Comment by Manishearth** [comment]
it wooooorks

**Comment by phansch** [comment]
LGTM! No idea about the unlinking error, though.

**Comment by Manishearth** [comment]
I'm merging, it's fine if appveyor is broken

**Comment by Manishearth** [comment]
(I want working PR CI as soon as possible)

**Comment by kennytm** [comment]
Looks like the unlink error is Windows-only https://github.com/rust-lang-nursery/rustup.rs/blob/22b6cdb8b000f9217af1dd5dd4e73ce032bdb25d/src/rustup/toolchain.rs#L374

**Pull request merged**
