### PR TITLE
Add lint for fallible impls of `From`

### LINKED ISSUE #691: lint `From<&str>` or `From<String>` implementations
suggest implementing `FromStr` instead

Why is this bad: Usually not all strings represent correct values, so using `FromStr` allows us to return a `Result` that includes error information.

### PR DESCRIPTION
**Pull request by HMPerson1**
Fixes #691.

Some notes:
 - I'm note sure about what to put for the error messages or documentation, so I would love any suggestions about that. Also maybe it should include a help string?
 - It reports the calls to `begin_panic` instead of the macro `panic!()` so it says `note: this error originates in a macro outside of the current crate`, which *might* be confusing.
 - It only detects calls to `unwrap` made with method-calling syntax; it won't detect UFCS syntax (i.e. `Option::unwrap(foo)`). AFAICT this applies to everything in `methods.rs` too.

### CODE REVIEW

**Comment by clarcharr** [comment]
I disagree with this lint because `FromStr` is being deprecated in favour of `From<&str>`, `TryFrom<&str>`, and co., and I'd rather not move backwards.

**Comment by HMPerson1** [comment]
Well once `TryFrom` stabilized, it's fairly easy to adapt this lint to say to use `TryFrom` instead of `FromStr`.

**Comment by clarcharr** [comment]
IMHO `From<String>` is a very valid trait to implement under that, and the idea is that `From` here indicates an infalliable conversion. The point of moving away from `FromStr` is because it doesn't have that kind of guarantee.

**Comment by HMPerson1** [comment]
Which is why this lint only fires when we see a `panic!()` or `unwrap` in the implementation of `from`, suggesting that the conversion is fallible. See the discussion in #691.

**Comment by oli-obk** [comment]
We can make the lint allow-by-default and have it suggest `TryFrom`. That would not start suggesting a soon-to-be-deprecated trait, but also not suggest stuff to stable users that they can't use.

**Comment by oli-obk** [comment]
I'd be willing to merge this as `allow`-by-default as it is, but to make it `warn`-by-default I'd like to run it on a bunch of big crates and see how it fares. Do you want to do this before merging, or do you want to make it `allow`?

**Comment by oli-obk** [comment]
Nevermind I'm stupid. It's already allow out of other reasons...

**Pull request merged**
