### PR TITLE
Fix author lint

### PR DESCRIPTION
**Pull request by gnieto**
The author lint was generating invalid code as shown on issue:
https://github.com/rust-lang-nursery/rust-clippy/issues/2442

I've changed the generated code to properly track cast
expressions.

Unfortunatelly, I've had to rewrite the `visit_decl` method, to
avoid that last if of the chain will be added. After looking at the code,
this last line was being added because of the `let x: char` part, but not
because of the `0x45df as char` expression.

It seems that let statements should not generate code on the author
lint, but I'm not sure that this is true or if I'm breaking
something on other code generation parts.

Finally, I've added a test for the author lint, but I'm not sure that
this needs to be added to the testsuite.

### CODE REVIEW

**Comment by oli-obk** [comment]
Statements should be producing code.

I'm not sure what you mean by "last line". What's the output without the visit_decl?

**Comment by gnieto** [comment]
Sorry for the long response, but there are some examples that may help to understand the issue.

Based on the code on the issue:

```
#[clippy(author)]
let x: char = 0x45df as char;
```

Currently (on master), it genrates the following code:

```
if_chain! {
    if let Expr_::ExprCast(ref expr, _) = stmt.node;
    if let Expr_::ExprLit(ref lit) = expr.node;
    if let LitKind::Int(17887, _) = lit.node;
    if match_qpath(expr, &["char"]);
    then {
        // report your lint here
    }
}
```

This code is wrong because it passes `expr` as argument to match_qpath, wich expects a QPath. In the code above, `expr` has type Expr, but not QPath.

Without my changes, and with the following example (note that I've removed the type hint):

```
#[clippy(author)]
let x = 0x45df as char;
```

The code generated is:

```
if_chain! {
    if let Expr_::ExprCast(ref expr, _) = stmt.node;
    if let Expr_::ExprLit(ref lit) = expr.node;
    if let LitKind::Int(17887, _) = lit.node;
    then {
        // report your lint here
    }
}
```

This implies that `if match_qpath(expr, &["char"]);` line is added because of the type hint.

Then, with the proposed changes, the generated code is:

```
if_chain! {
    if let Expr_::ExprCast(ref expr, ref cast_ty) = stmt.node;
    if let Ty_::TyPath(ref qp) = cast_ty.node;
    if match_qpath(qp, &["char"]);
    if let Expr_::ExprLit(ref lit) = expr.node;
    if let LitKind::Int(17887, _) = lit.node;
    then {
        // report your lint here
    }
}
```

And without the `visit_decl`, the generated code is:

```
if_chain! {
    if let Expr_::ExprCast(ref expr, ref cast_ty) = stmt.node;
    if let Ty_::TyPath(ref qp) = cast_ty.node;
    if match_qpath(qp, &["char"]);
    if let Expr_::ExprLit(ref lit) = expr.node;
    if let LitKind::Int(17887, _) = lit.node;
    if match_qpath(expr, &["char"]);
    then {
        // report your lint here
    }
} 
```

Again, this produces broken code because it adds the last line `if match_qpath(expr, &["char"]);`, which is incorrect as I said before.

Why this line is added? As the local declaration contains a Ty, it will end calling to `visit_qpath` and `self.current` will contain the last used label: `expr`.

I'm thinking on a change that would avoid rewritting the `visit_decl` method. I'll push a change on this PR with a new approach.

**Comment by gnieto** [comment]
I've added this changes: 3ac84b2542ec1c4caeab54239c67202113c82ea0.

Basically, I'm moving `visit_qpath` to a private function on `PrintVisitor`, to prevent that it will be called on some unexpected scenarios (as the one I've explained on the previous comment). I've also removed the redefintion of ` visit_decl`.

Can you check it now?

**Comment by oli-obk** [comment]
Thanks for the detailed explanation and the error avoiding fix!

**Pull request merged**
