### PR TITLE
adding to restriction a lint that check for multiple inherent implementations

### PR DESCRIPTION
**Pull request by mockersf**
for #414

warn on each subsequent implementation of a `struct`, with a note showing the first implementation

### CODE REVIEW

**Comment by mockersf** [comment]
oh well latest nightly is not happy with clippy  😢 
FF `#![feature(macro_at_most_once_rep)]` is needed as macros `declare_lint` and `lint_array` [were changed](https://github.com/rust-lang/rust/commit/0e53b788309c446788335b4fbb478490eea1e667)
then there are a lot of errors like `no field 'name' on type '&rustc::hir::Field'` because of [another change](https://github.com/rust-lang/rust/commit/189c0a1297f9341fd25f4c0a0f09c47610cdcbf1)

**Comment by mati865** [comment]
Nightly breakage is handled in https://github.com/rust-lang-nursery/rust-clippy/pull/2817

**Comment by phansch** [comment]
retriggering travis

**Comment by mati865** [comment]
@phansch It needs to be rebased on top of master to make Travis pass.

**Comment by Manishearth** [comment]
looks like you cherry picked the rustup? Please rebase over master instead 😄

**Comment by mockersf** [comment]
my bad, my git-fu is not that good

**Comment by mockersf** [comment]
one of the integration build failed with
```
error: component download failed for rust-docs-x86_64-unknown-linux-gnu
info: caused by: could not download file from 'https://static.rust-lang.org/dist/2018-05-29/rust-docs-nightly-x86_64-unknown-linux-gnu.tar.xz' to '/home/travis/.rustup/downloads/dafb4b05358273e2b1ce3e290a5d3a3a5ddde75ec3cb9431c028c3e1e4f7cea4.partial'
info: caused by: http request returned an unsuccessful status code: 503
```

**Pull request merged**
