### PR TITLE
Fix verbose_bit_mask off by one error

### LINKED ISSUE #1940: verbose_bit_mask
Correct me if I'm wrong, but for `x = 0b10000u16`, `x.trailing_zeros() > 4` and `x & 0b1111 == 0` are not equivalent. Shouldn't the advice be `>=`?

### PR DESCRIPTION
**Pull request by mati865**
Fixes #1940 

What would be preferred solution, replacing `>` with `>=` or incrementing `n.count_ones()`?

### CODE REVIEW

**Comment by mati865** [comment]
Right now clippy builds only with version `nightly-2017-08-09`.

**Comment by oli-obk** [comment]
> What would be preferred solution, replacing > with >= or incrementing n.count_ones()?

I think `>=`. Adding one to something is always a little ugly imo

**Comment by mati865** [comment]
Currently it's `>=` solution and tests are passing with nightly-2017-08-09.

**Comment by oli-obk** [comment]
Yea, I'm working on the rustup right now: https://github.com/rust-lang-nursery/rust-clippy/pull/1947

**Comment by oli-obk** [comment]
Thanks for the quick fix!

**Pull request merged**
