### PR TITLE
Rust upgrade to rustc 1.23.0-nightly (f0fe716db 2017-10-30)

### LINKED ISSUE #2192: Clippy 0.0.167 fails to build on nightly 2017-10-30: vis fragment specifier is experimental and subject to change
``` 
$ rustc --version
rustc 1.23.0-nightly (f0fe716db 2017-10-30)
```

```
   Compiling clippy_lints v0.0.167
error: :vis fragment specifier is experimental and subject to change (see issue #41022)
 --> <declare_lint macros>:1:3
  |
1 | ( $ vis : vis $ NAME : ident , $ Level : ident , $ desc : expr ) => (
  |   ^^^^^^^^^^^
  |
  = help: add #![feature(macro_vis_matcher)] to the crate attributes to enable
```

### PR DESCRIPTION
**Pull request by Manishearth**
fixes #2192

### CODE REVIEW

**Comment by Manishearth** [comment]
@kennytm looks like lint_without_lint_pass was broken; care to take a look?

**Comment by kennytm** [comment]
Reproduced locally. The lint did not fire. Currently checking why.

**Comment by kennytm** [comment]
@Manishearth Please apply these diff:

<details><summary>1. Get rid of the <code>lt.is_elided()</code> check from <code>internal_lints.rs</code> (why is it here in the first place?)</summary>

```diff
diff --git a/clippy_lints/src/utils/internal_lints.rs b/clippy_lints/src/utils/internal_lints.rs
index a35b034d..6e62f967 100644
--- a/clippy_lints/src/utils/internal_lints.rs
+++ b/clippy_lints/src/utils/internal_lints.rs
@@ -161,16 +161,13 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for LintWithoutLintPass {
 
 fn is_lint_ref_type(ty: &Ty) -> bool {
     if let TyRptr(
-        ref lt,
+        _,
         MutTy {
             ty: ref inner,
             mutbl: MutImmutable,
         },
     ) = ty.node
     {
-        if lt.is_elided() {
-            return false;
-        }
         if let TyPath(ref path) = inner.node {
             return match_qpath(path, &paths::LINT);
         }
```

</details>

<details><summary>2. The module <code>rustc::lint::*</code> becomes just <code>lint::*</code>, so update <code>paths.rs</code></summary>

```diff
diff --git a/clippy_lints/src/utils/paths.rs b/clippy_lints/src/utils/paths.rs
index 96ccddaf..95e14609 100644
--- a/clippy_lints/src/utils/paths.rs
+++ b/clippy_lints/src/utils/paths.rs
@@ -41,8 +41,8 @@ pub const IO_READ: [&str; 3] = ["std", "io", "Read"];
 pub const IO_WRITE: [&str; 3] = ["std", "io", "Write"];
 pub const ITERATOR: [&str; 4] = ["core", "iter", "iterator", "Iterator"];
 pub const LINKED_LIST: [&str; 3] = ["alloc", "linked_list", "LinkedList"];
-pub const LINT: [&str; 3] = ["rustc", "lint", "Lint"];
-pub const LINT_ARRAY: [&str; 3] = ["rustc", "lint", "LintArray"];
+pub const LINT: [&str; 2] = ["lint", "Lint"];
+pub const LINT_ARRAY: [&str; 2] = ["lint", "LintArray"];
 pub const MEM_FORGET: [&str; 3] = ["core", "mem", "forget"];
 pub const MEM_UNINIT: [&str; 3] = ["core", "mem", "uninitialized"];
 pub const MEM_ZEROED: [&str; 3] = ["core", "mem", "zeroed"];
```

</details>

<details><summary>3. Some minor UI test fix.</summary>

```diff
diff --git a/tests/ui/lint_pass.rs b/tests/ui/lint_pass.rs
index b576f72e..29c93e74 100644
--- a/tests/ui/lint_pass.rs
+++ b/tests/ui/lint_pass.rs
@@ -2,7 +2,6 @@
 #![feature(rustc_private)]
 #![feature(macro_vis_matcher)]
 
-
 #![warn(lint_without_lint_pass)]
 
 #[macro_use] extern crate rustc;
```

</details>

**Comment by Manishearth** [comment]
Thanks, @kennytm !

**Pull request merged**
