### PR TITLE
Consistently call it "Clippy", not clippy or rust-clippy

### PR DESCRIPTION
**Pull request by dwijnand**
As per discussion on the Clippy 1.0 RFC

### CODE REVIEW

**Comment by phansch** [comment]
Seems sensible, thanks! ([link to discussion](https://github.com/rust-lang/rfcs/pull/2476/commits/3bd030596d9f056726bc04ed3487850f22b1b7b7#r195585597))

**Comment by dwijnand** [comment]
Next up renaming the repo 😉

**Comment by Manishearth** [comment]
Idk, rust-foo for repo naming is pretty normal

**Comment by dwijnand** [comment]
Pretty common, indeed. Especially when attached to something generic, like rust-cookbook, rust-mode, or rust.vim.

But "clippy" isn't generic in the same way, although it is a recycled name. Had it been named rustlint it would've lived happily ever after with its rustfmt and rustfix buddies, but left cargo without a friend. :smile:

**Comment by flip1995** [comment]
I would stay with rust-clippy especially because it is a recycled name. The first result when googling Clippy (sadly) still is the Wikipedia article for the good ol' office assistant and not this repo. Because Clippy is actually helpful, we should separate us from the office assistant. 😄

**Comment by dwijnand** [comment]
Google-fu is required to find cargo too 😀

**Pull request merged**
