### PR TITLE
Fix `ImplItem`s being ignored

### LINKED ISSUE #2356: while let on iterator is a false positive in some cases?
I have the following code from `Vec`'s implementation:

```rust
  fn extend_desugared<I: Iterator<Item = T>>(&mut self, mut iterator: I) {
        while let Some(element) = iterator.next() {
            let len = self.len();
            if len == self.capacity() {
                let (lower, _) = iterator.size_hint();
                self.reserve(lower.saturating_add(1));
            }
            unsafe {
                ::std::ptr::write(self.get_unchecked_mut(len), element);
                // NB can't overflow since we would have had to alloc the
                // address space
                self.move_tail(1);
            }
        }
    }
```

How should one transform this loop to a `for`-loop? The help is completely insufficient:

```shell
^ help: try: `for element in iterator { .. }`
```

Note that the `while let` loop does not move iterator (it does not implement copy) but a `for element in iterator { }` loop would move iterator, making it unusable in the body.

### PR DESCRIPTION
**Pull request by HMPerson1**
Fixes #2356

Apparently `NodeImplItem` is distinct from `NodeItem`, but we want both.

### CODE REVIEW

**Comment by oli-obk** [comment]
Makes sense.

Can you add the test from the issue as a regression test?

**Comment by HMPerson1** [comment]
Should it be in `while_loop.rs` with the other tests for `while_let_on_iterator`? Or is there a better place for testing utility functions?

**Comment by oli-obk** [comment]
Nah, just throw in the example from the issue. Put it in a separate file though.

**Comment by HMPerson1** [comment]
I found some other cases where `ImplItem`s were forgotten about. Might as well fix those too.

**Comment by oli-obk** [comment]
Great fixes!

**Pull request merged**
