### PR TITLE
[WIP] rustup: fix build with rustc 1.31.0-nightly (cae6efc37 2018-10-27)

### PR DESCRIPTION
**Pull request by matthiaskrgr**
I couldn't run tests yet due to #3367

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Ok, nevermind, the change compiles but tests are broken afterwards :/

**Comment by phansch** [comment]
Can you try and point compiletest-rs to master?

**Comment by matthiaskrgr** [comment]
I already did but useless_clone tests failed

**Comment by matthiaskrgr** [comment]
tests pass now

**Comment by matthiaskrgr** [comment]
I have been thinking about that too.
We would need to pin rustc to "nighty" instead of "master" then, right?

**Pull request merged**
