### PR TITLE
fix build of build.rs

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by mati865** [comment]
It shouldn't be required at all, Clippy is [2018 crate already](https://github.com/rust-lang-nursery/rust-clippy/blob/8ef759e0273ad97f1acbb1ea9f94322aa2a20147/Cargo.toml#L20)

**Comment by matthiaskrgr** [comment]
I know.
Maybe there's a bug of how build.rs is handled with editions?

I was able to have
````rust
#![feature(rust_2018_preview)]
#![warn(rust_2018_idioms)]

extern crate ansi_term;
extern crate rustc_version;

use ansi_term::Colour::Red;
use rustc_version::{version_meta, version_meta_for, Channel, Version, VersionMeta};
use std::env;
````
without triggering any warning.

**Comment by mati865** [comment]
@matthiaskrgr does it work if you add `#![feature(rust_2018_preview)]` and remove all `extern crate...`?

**Comment by matthiaskrgr** [comment]
Nope, the build errors return when I do that.

**Comment by mati865** [comment]
I think you should reported it to rust/cargo (if it's not reported already) and add comment with link to the issue. It's a workaround and somebody could remove it prematurely.

**Comment by phansch** [comment]
Going ahead and closing this because the cargo PR has been merged. We just need to wait for cargo to be updated in rustc and the following nightly.

**Pull request closed without merging**
