### PR TITLE
if_let_redundant_pattern_matching: use Span.to() instead of Span.with_hi() to fix crash.

### LINKED ISSUE #3064: crash checking ws-rs
clippy @ 07c2e614362ad8645eafe771e672a65f92e3b9a2

````
git clone https://github.com/tomusdrw/ws-rs
cd ws-rs
git checkout f12d19c4
RUST_BACKTRACE=full cargo clippy
````
````
warning: redundant pattern matching, consider using `is_some()`
   --> src/connection.rs:446:28
    |
446 |                     if let Some(_) = try!(self.socket.try_write_buf(res)) {
    |                            ^^^^^^^
    |
    = note: #[warn(if_let_redundant_pattern_matching)] on by default
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#if_let_redundant_pattern_matching
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DistinctSources(DistinctSources { begin: (Real("src/connection.rs"), BytePos(21191)), end: (Macros("try"), BytePos(9154066)) })', libcore/result.rs:983:5
stack backtrace:
   0:     0x7fe913b8633e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h1410ee01a7694834
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fe913b5f0f6 - std::sys_common::backtrace::print::h1962f4c30d928b1d
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x7fe913b5cbdd - std::panicking::default_hook::{{closure}}::h66071f1a30ddacaa
                               at libstd/panicking.rs:211
   3:     0x7fe913b5c950 - std::panicking::default_hook::h8288f681d56575d2
                               at libstd/panicking.rs:227
   4:     0x7fe915ab8d45 - rustc::util::common::panic_hook::hba0ca6620bd19f58
   5:     0x7fe913b5d363 - std::panicking::rust_panic_with_hook::h46fa5def146c1328
                               at libstd/panicking.rs:479
   6:     0x7fe913b5cf09 - std::panicking::continue_panic_fmt::h9933c8abec1f0661
                               at libstd/panicking.rs:390
   7:     0x7fe913b5ce05 - rust_begin_unwind
                               at libstd/panicking.rs:325
   8:     0x7fe913bf004b - core::panicking::panic_fmt::h380215f9f52a35ae
                               at libcore/panicking.rs:77
   9:     0x7fe91499d928 - core::result::unwrap_failed::h8ea94e54284075b9
  10:     0x7fe914994987 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once::hfb8ae452633bec7d
  11:     0x7fe914989ad3 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h921f05b2323425bd
  12:     0x7fe9149721d0 - <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit::h909682efa78cf3e9
  13:     0x7fe914998950 - rustc_errors::Handler::emit_db::hfcb961d44c43aac1
  14:     0x7fe914984467 - rustc_errors::diagnostic_builder::DiagnosticBuilder::emit::h53d2c1622f8c3629
  15:     0x56057d32568d - <clippy_lints::utils::DiagnosticWrapper<'a> as core::ops::drop::Drop>::drop::h7d1ae4b5af7fb12a
                               at clippy_lints/src/utils/mod.rs:503
  16:     0x56057d728b60 - core::ptr::drop_in_place::he90d8dbd9f404128
                               at /checkout/src/libcore/ptr.rs:59
  17:     0x56057d33334b - clippy_lints::utils::span_lint_and_then::hd6bbc0c589e1a550
                               at clippy_lints/src/utils/mod.rs:564
  18:     0x56057d7b2e40 - <clippy_lints::if_let_redundant_pattern_matching::Pass as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr::hb1147daf5e9f9dc2
                               at clippy_lints/src/if_let_redundant_pattern_matching.rs:73
  19:     0x7fe915b523f0 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h6e384de84dd40895
  20:     0x7fe915b5452e - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block::hc4f8c19d2df9b157
  21:     0x7fe915b524bb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h6e384de84dd40895
  22:     0x7fe915b548f1 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_arm::h8ab57bc399e80bef
  23:     0x7fe915a1130e - rustc::hir::intravisit::walk_expr::h5017cc1c6b29dccf
  24:     0x7fe915b524bb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h6e384de84dd40895
  25:     0x7fe915b54545 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block::hc4f8c19d2df9b157
  26:     0x7fe915b524bb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h6e384de84dd40895
  27:     0x7fe915b548f1 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_arm::h8ab57bc399e80bef
  28:     0x7fe915a1130e - rustc::hir::intravisit::walk_expr::h5017cc1c6b29dccf
  29:     0x7fe915b524bb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h6e384de84dd40895
  30:     0x7fe915b5452e - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block::hc4f8c19d2df9b157
  31:     0x7fe915b524bb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h6e384de84dd40895
  32:     0x7fe915b514d0 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body::hc89753e3db8d528d
  33:     0x7fe915b51309 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body::h04e2401531baebc6
  34:     0x7fe915b52c3e - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn::ha1e16b612565220c
  35:     0x7fe915a067dd - rustc::hir::intravisit::walk_impl_item::h64d21d0b16675478
  36:     0x7fe915b55bac - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item::hebffac8a38540adf
  37:     0x7fe915a093f9 - rustc::hir::intravisit::walk_impl_item_ref::h804e9d888eb32c2d
  38:     0x7fe9159da31e - rustc::hir::intravisit::walk_item::h8881fe437567c17a
  39:     0x7fe915b519e9 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h74f7f8a6eec1ca33
  40:     0x7fe915b53eeb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::hf654389fa7a840ae
  41:     0x7fe9159da17d - rustc::hir::intravisit::walk_item::h8881fe437567c17a
  42:     0x7fe915b519e9 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h74f7f8a6eec1ca33
  43:     0x7fe915b53eeb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::hf654389fa7a840ae
  44:     0x7fe9159ce00b - rustc::hir::intravisit::walk_crate::h27bb06cc67cea340
  45:     0x7fe915b5b090 - rustc::lint::context::check_crate::h95ef6051dbd5cdb2
  46:     0x7fe916845982 - rustc::util::common::time::h30101ed3c848058a
  47:     0x7fe916813e15 - rustc::ty::context::tls::enter_context::h6937f3691b4df493
  48:     0x7fe9168aea4a - <std::thread::local::LocalKey<T>>::with::hdfdf81913852ed5c
  49:     0x7fe916914add - rustc::ty::context::TyCtxt::create_and_enter::h060fb9854d3ecc5a
  50:     0x7fe91685f6c8 - rustc_driver::driver::compile_input::hc2e2c0ed6ab93a1c
  51:     0x7fe916900735 - rustc_driver::run_compiler_with_pool::h2b086979f97a3943
  52:     0x7fe91685b32e - syntax::with_globals::hb19a09c6ec76932b
  53:     0x7fe9168ff818 - rustc_driver::run_compiler::haf1344c872c816c3
  54:     0x56057d20d4c8 - clippy_driver::main::h0d31c47ac76d2c18
                               at src/driver.rs:131
  55:     0x56057d21cadf - std::rt::lang_start::{{closure}}::h6921cdcae5ed4284
                               at /checkout/src/libstd/rt.rs:74
  56:     0x7fe913b5cda2 - std::panicking::try::do_call::hc3bbfe344c9dd679
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  57:     0x7fe913b9ba19 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  58:     0x7fe913b73955 - std::rt::lang_start_internal::h6831243cb445d5dc
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  59:     0x56057d21cab7 - std::rt::lang_start::h12b7cda8fbefcfd9
                               at /checkout/src/libstd/rt.rs:74
  60:     0x56057d20d919 - main
  61:     0x7fe9138e3222 - __libc_start_main
  62:     0x56057d1ef02d - _start
  63:                0x0 - <unknown>
query stack during panic:
end of query stack
error: Could not compile `ws`.


````

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Fixes #3064

I didn't manage to get a small reproducer yet.
The crash is related to ws-rs connection.rs.

### CODE REVIEW

**Comment by phansch** [comment]
Yea, finding a test case for this will not be easy, because the span seems to go across two (or more) files.

We have one test case for such a span here:

https://github.com/rust-lang-nursery/rust-clippy/blob/67d85bc47dbfa6c5d37bdfe09e45b746e31c4804/tests/ui/implicit_hasher.rs#L86-L91

Do you want to try to create a test case?

**Comment by matthiaskrgr** [comment]
Hrm.. I spent some more time on this but it seems the example I am trying does not repro any crash :(
lib.rs:
````rust
use std::io;

mod macros;

fn main() {
    println!("Hello, world!");
}

pub fn a() -> Result<u8, u8> {
	Ok(4)
}


pub fn crash(n: Option<u32>) -> Result<(), io::Error>  {
	match n {
		Some(_) => {
			match someoption!() {
                                  Ok(_) =>  { if true {}},
                                   _ => {},
			}
		}
	        _ => {}
	}
	Ok(())
}
````
macros.rs:
````rust

#[macro_export]
macro_rules! someoption {
    () => {{
        Ok(3) as Result<i32, io::Error>
    }};
}
````

**Comment by matthiaskrgr** [comment]
rebased.

**Comment by phansch** [comment]
another crash bites the [dust](https://www.youtube.com/watch?v=rY0WxgSXdEE) :notes: :notes:

**Pull request merged**
