### PR TITLE
Upcoming breakage

### LINKED ISSUE #2838: Build fail on nightly (8afb89493 2018-06-08)
Master branch fails to build on latest nightly:
```
error[E0053]: method `build_controller` has an incompatible type for trait
  --> src/driver.rs:72:5
   |
72 |     fn build_controller(&mut self, sess: &Session, matches: &getopts::Matches) -> driver::CompileController<'a> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::boxed::Box`, found mutable reference
   |
   = note: expected type `fn(std::boxed::Box<ClippyCompilerCalls>, &rustc::session::Session, &getopts::Matches) -> rustc_driver::driver::CompileController<'a>`
              found type `fn(&mut ClippyCompilerCalls, &rustc::session::Session, &getopts::Matches) -> rustc_driver::driver::CompileController<'a>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0053`.
```

### PR DESCRIPTION
**Pull request by mati865**
Do **not** merge until next nightly build is produced (or merge to different branch).
Builds and passes tests with rust commit c131bdcaff68d35f96e954baac4340206779335f

Fixes #2838

### CODE REVIEW

**Comment by oli-obk** [comment]
Cool! Thanks. That PR allows us to do a really good refactoring dropping most of the boilerplate. If you feel motivated, have a look at the PR's doc example on how to inject a handler closure. We should be able to do the same here and remove all that boilerplate

**Comment by mati865** [comment]
Tests are passing and it was easier than I feared (all hail ctrl-c and ctrl-v).

Be careful during review though because:
no_idea
(Maybe not so bad but still it's pretty accurate)

**Comment by oli-obk** [comment]
Retriggering travis

**Comment by oli-obk** [comment]
Thanks for being ahead of the curve!

**Pull request merged**
