### PR TITLE
Stop linting `assert!(x == y)`

### LINKED ISSUE #2090: Stop linting `assert!(x == y)`
While RFC 2011 isn't implemented yet, the earlier we stop telling people to rewrite their asserts, the less they will be pissed once we tell them to change it back :)

### PR DESCRIPTION
**Pull request by thelearnerofcode**
fixes #2090

### CODE REVIEW

**Comment by clarcharr** [comment]
I think that instead of removing the lint entirely, it should just be switched to allow by default.

**Comment by oli-obk** [comment]
Why should we keep this lint? Can you elaborate on that?

We should not add the inverse lint until the RFC is implemented.

**Comment by Manishearth** [comment]
> I think that instead of removing the lint entirely, it should just be switched to allow by default. 

We already have a mechanism for deprecating lints; we can just use that. This makes the lint do nothing and warn on being used, but won't suddenly break code that has `#[allow(name_of_lint)]` because the lint is suddenly unknown.

On that note, this PR does not do that, it should.

**Comment by oli-obk** [comment]
@thelearnerofcode friendly ping

You need to

1. rebase
2. add the removed lint to the list of deprecated lints

**Comment by oli-obk** [comment]
Has been fixed in another PR.

**Pull request closed without merging**
